### PR TITLE
Add CatBlock feature

### PR DESCRIPTION
**Pull request by tomasko126**
@adblock-origin/extension-team 
Guys, I've imported a feature for replacing ads with a pictures of cats (or whatever you want) - internally named CatBlock, which can be enabled on Options page -> General tab.
Please test it on some pages e.g. on http://reddit.com. Feedback would be appreciated.

### CODE REVIEW

**Comment by kpeckett** [comment]
The CatBlock tab still shows even when CatBlock is disabled on the General tab. Should the CatBlock tab be renamed to "Features" and add that in there, and hide if disabled?

**Comment by tomasko126** [comment]
@kpeckett I've just adjusted appearance of CatBlock options in menu, so it doesn't appear when it's disabled.

**Comment by Dolanko** [comment]
Okay so I tried CatBlock on reddit.com and the cat showed up. When I turned the feature off, cat didn't show up, exactly as intended.

**Comment by tomasko126** [comment]
@kpeckett @Dolanko Thanks for testing, merging now..

**Pull request merged**
